export const SAVE_PROPINSI_REQUEST = 'SAVE_PROPINSI_REQUEST';
export const SAVE_PROPINSI_SUCCESS = 'SAVE_PROPINSI_SUCCESS';
export const SAVE_PROPINSI_FAILURE = 'SAVE_PROPINSI_FAILURE';

export const DELETE_PROPINSI_REQUEST = 'DELETE_PROPINSI_REQUEST';
export const DELETE_PROPINSI_SUCCESS = 'DELETE_PROPINSI_SUCCESS';
export const DELETE_PROPINSI_FAILURE = 'DELETE_PROPINSI_FAILURE';

export const FIND_PROPINSI_REQUEST = 'FIND_PROPINSI_REQUEST';
export const FIND_PROPINSI_SUCCESS = 'FIND_PROPINSI_SUCCESS';
export const FIND_PROPINSI_FAILURE = 'FIND_PROPINSI_FAILURE';

export const FIND_PROPINSIS_REQUEST = 'FIND_PROPINSIS_REQUEST';
export const FIND_PROPINSIS_SUCCESS = 'FIND_PROPINSIS_SUCCESS';
export const FIND_PROPINSIS_FAILURE = 'FIND_PROPINSIS_FAILURE';


export const SAVE_KONTRASEPSI_REQUEST = 'SAVE_KONTRASEPSI_REQUEST';
export const SAVE_KONTRASEPSI_SUCCESS = 'SAVE_KONTRASEPSI_SUCCESS';
export const SAVE_KONTRASEPSI_FAILURE = 'SAVE_KONTRASEPSI_FAILURE';

export const DELETE_KONTRASEPSI_REQUEST = 'DELETE_KONTRASEPSI_REQUEST';
export const DELETE_KONTRASEPSI_SUCCESS = 'DELETE_KONTRASEPSI_SUCCESS';
export const DELETE_KONTRASEPSI_FAILURE = 'DELETE_KONTRASEPSI_FAILURE';

export const FIND_KONTRASEPSI_REQUEST = 'FIND_KONTRASEPSI_REQUEST';
export const FIND_KONTRASEPSI_SUCCESS = 'FIND_KONTRASEPSI_SUCCESS';
export const FIND_KONTRASEPSI_FAILURE = 'FIND_KONTRASEPSI_FAILURE';

export const FIND_KONTRASEPSIS_REQUEST = 'FIND_KONTRASEPSIS_REQUEST';
export const FIND_KONTRASEPSIS_SUCCESS = 'FIND_KONTRASEPSIS_SUCCESS';
export const FIND_KONTRASEPSIS_FAILURE = 'FIND_KONTRASEPSIS_FAILURE';


export const DELETE_PEMAKAIKONTRASEPSI_REQUEST = 'DELETE_PEMAKAIKONTRASEPSI_REQUEST';
export const DELETE_PEMAKAIKONTRASEPSI_SUCCESS = 'DELETE_PEMAKAIKONTRASEPSI_SUCCESS';
export const DELETE_PEMAKAIKONTRASEPSI_FAILURE = 'DELETE_PEMAKAIKONTRASEPSI_FAILURE';

export const SAVE_PEMAKAIKONTRASEPSI_REQUEST = 'SAVE_PEMAKAIKONTRASEPSI_REQUEST';
export const SAVE_PEMAKAIKONTRASEPSI_SUCCESS = 'SAVE_PEMAKAIKONTRASEPSI_SUCCESS';
export const SAVE_PEMAKAIKONTRASEPSI_FAILURE = 'SAVE_PEMAKAIKONTRASEPSI_FAILURE';

export const FIND_PEMAKAIKONTRASEPSI_REQUEST = 'FIND_PEMAKAIKONTRASEPSI_REQUEST';
export const FIND_PEMAKAIKONTRASEPSI_SUCCESS = 'FIND_PEMAKAIKONTRASEPSI_SUCCESS';
export const FIND_PEMAKAIKONTRASEPSI_FAILURE = 'FIND_PEMAKAIKONTRASEPSI_FAILURE';

export const FIND_PEMAKAIKONTRASEPSIS_REQUEST = 'FIND_PEMAKAIKONTRASEPSIS_REQUEST';
export const FIND_PEMAKAIKONTRASEPSIS_SUCCESS = 'FIND_PEMAKAIKONTRASEPSIS_SUCCESS';
export const FIND_PEMAKAIKONTRASEPSIS_FAILURE = 'FIND_PEMAKAIKONTRASEPSIS_FAILURE';
